traefik:
  globalArguments:
    - "--global.checknewversion=false"
    - "--global.sendanonymoususage=false"
    # - "--api.insecure=false"
  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"
  image:
    name: traefik
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 70
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 70
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Pods
            value: 1
            periodSeconds: 60
  service:
    enabled: true
    type: LoadBalancer
    spec:
      externalTrafficPolicy: Local
  affinity: {}
  tolerations: []
  logs:
    general:
      level: INFO
  # tlsStore:
  #   default:
  #     defaultCertificate:
  #       secretName: traefik-cert
  ingressRoute:
    dashboard:
      enabled: false
